create table if not exists public.betfair_quotes (
  id bigint generated by default as identity primary key,
  market_id text,
  data_type text not null check (data_type in ('catalogue','book')),
  payload jsonb not null,
  received_at timestamptz not null default now()
);

create index if not exists betfair_quotes_type_received_idx
  on public.betfair_quotes (data_type, received_at desc);

create index if not exists betfair_quotes_market_received_idx
  on public.betfair_quotes (market_id, received_at desc);

-- Il bridge usa SUPABASE_SERVICE_ROLE_KEY lato Vercel, quindi le RLS policy
-- non sono necessarie per le chiamate del bridge. Se RLS è già attiva,
-- resta comunque bypassata dalla service role key.
